In [15]:
import numpy as np

In [358]:
numbers = np.array([1,2,3])
mixed_type = np.array([True, "two", 3])

# numbers[2] != mixed_type[2]
print(numbers[2] == 3)
print(mixed_type[2] == 3)

print(numbers.dtype)
print(mixed_type.dtype)

True
False
int64
<U21


In [491]:
numbers = np.array([1,2,3,4,5])
print(numbers[3:])
print(numbers[1:4:])
print(numbers[::-2])

[4 5]
[2 3 4]
[5 3 1]


In [501]:
numbers = np.array([1,2,3,4,5])
# element
numbers[0] = 0
print(numbers)
# slice
numbers[1:4] = [88,99,88]
print(numbers)
# even
numbers[::2] = 0
print(numbers)

[0 2 3 4 5]
[ 0 88 99 88  5]
[ 0 88  0 88  0]


In [473]:
numbers = np.array([1,2,3])

print(np.append(numbers,4))
print(np.append(numbers,[4,5,6]))
print(np.insert(numbers, 1, 9))
print(np.insert(numbers, 1, [9,9]))

[1 2 3 4]
[1 2 3 4 5 6]
[1 9 2 3]
[1 9 9 2 3]


In [527]:
numbers = np.array([0,1,2,3,4,5])

# remove indexes
print(np.delete(numbers,3))
print(np.delete(numbers,[1,4,2]))

# remove values
print(numbers[numbers != 2])

[0 1 2 4 5]
[0 3 5]
[0 1 3 4 5]


In [667]:
numbers = np.array([1,2,3,7,8,9])

print(np.where(numbers > 7 , 0, numbers))
print(np.clip(numbers,2,7))
print(numbers > 3)

[1 2 3 7 0 0]
[2 2 3 7 7 7]
[False False False  True  True  True]


In [665]:
numbers = np.array([1,2,3,4,5])
numbers_b = numbers
numbers_copy = numbers.copy()

numbers[:3]=0

print(numbers_b)
print(numbers_copy)

[0 0 0 4 5]
[1 2 3 4 5]


In [555]:
matrix = np.array([[0,1,2],[10,11,12], [20,21,22]])
print(matrix)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [668]:
# matrix = np.array([[0,1,2],[10,11,12], [20,21,22]])
print(matrix[0,1], "\n")
# array[row(start:stop:step)
print(matrix[0,:], "\n") # row 
print(matrix[:,2], "\n") # col 
print(matrix[0:2,0:2], "\n") # slice 
print(matrix[2::-1,2::-1]) # negative step

1 

[0 1 2] 

[ 2 12 22] 

[[ 0  1]
 [10 11]] 

[[22 21 20]
 [12 11 10]
 [ 2  1  0]]


In [570]:
matrix = np.array([[0,1,2],[10,11,12], [20,21,22]])

matrix[1,1] = 99
print(matrix, "\n")

# replace every element in a row
matrix[1,:] = [80, 81, 82]
print(matrix, "\n")

# replace even elements in a col
matrix[0::2,1] = 77
print(matrix)

[[ 0  1  2]
 [10 99 12]
 [20 21 22]] 

[[ 0  1  2]
 [80 81 82]
 [20 21 22]] 

[[ 0 77  2]
 [80 81 82]
 [20 77 22]]


In [593]:
matrix = np.array([[0,1,2],[10,11,12], [20,21,22]])
print(np.where(matrix % 3 == 0, 0, matrix), "\n")
print(np.where(matrix[2] % 3 == 0, 0, matrix[2]), "\n") #where with one row

print(np.clip(matrix,8,18), "\n")
print(np.clip(matrix[:,2],3,13)) #clip with one col

[[ 0  1  2]
 [10 11  0]
 [20  0 22]] 

[20  0 22] 

[[ 8  8  8]
 [10 11 12]
 [18 18 18]] 

[ 3 12 13]


In [562]:
matrix = np.array([[0,1,2],[10,11,12], [20,21,22]])
print(np.concatenate((matrix, [[30,31,32]])))

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [565]:
matrix = np.array([[0,1,2],[10,11,12], [20,21,22]])
print(np.vstack([
    matrix,
    [30,31,32], 
    [40,41,42]])) # add row

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]]


In [566]:
matrix = np.array([[0,1,2],[10,11,12], [20,21,22]])
print(np.hstack([
      matrix,
      [[3,4],
       [13,14],
       [23,24]
      ]]))

# print("dimenssions: ", five_by_five.ndim) 
# print("shape: ", five_by_five.shape)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]


In [443]:
matrix = np.array([[0,1,2],[10,11,12], [20,21,22]])

row_del = np.delete(matrix, 1, 0)
print(row_del, "\n")

col_del = np.delete(matrix, 1, 1)
print(col_del, "\n")

[[ 0  1  2]
 [20 21 22]] 

[[ 0  2]
 [10 12]
 [20 22]] 



In [627]:
tensor = np.array([[[0,1],[10,11]],
                   [[20,21],[30,31]],
                   [[40,41], [50,51]]
                 ])
print("shape:", tensor.shape, "\n")
zero_del = np.delete(tensor, 1, 0)
print(zero_del, "\n", "shape:", zero_del.shape, "\n")

one_del = np.delete(tensor, 1, 1)
print(one_del, "\n", "shape:", one_del.shape, "\n")

two_del = np.delete(tensor, 1, 2)
print(two_del, "\n", "shape:", two_del.shape, "\n")
print(zero_del.ndim, one_del.ndim, two_del.ndim)

shape: (3, 2, 2) 

[[[ 0  1]
  [10 11]]

 [[40 41]
  [50 51]]] 
 shape: (2, 2, 2) 

[[[ 0  1]]

 [[20 21]]

 [[40 41]]] 
 shape: (3, 1, 2) 

[[[ 0]
  [10]]

 [[20]
  [30]]

 [[40]
  [50]]] 
 shape: (3, 2, 1) 

3 3 3


In [636]:
array = np.array([[[0,1],[10,11]],
                  [[20,21],[30,31]],
                  [[40,41], [50,51]]])
print(array.reshape(3,4), "\n")
print(array.reshape(2,2,1,3), "\n")
print(array.reshape(12))

[[ 0  1 10 11]
 [20 21 30 31]
 [40 41 50 51]] 

[[[[ 0  1 10]]

  [[11 20 21]]]


 [[[30 31 40]]

  [[41 50 51]]]] 

[ 0  1 10 11 20 21 30 31 40 41 50 51]


In [433]:
zeros = np.zeros((2,3))
print(zeros, "\n")

ones = np.ones((2,3,4), dtype="int8")
print(ones, "\n")
               
threes =  np.full((2,2,2),3)
print(threes)

[[0. 0. 0.]
 [0. 0. 0.]] 

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

[[[3 3]
  [3 3]]

 [[3 3]
  [3 3]]]


In [671]:
# random decimals
print(np.random.random((2,2,2)), "\n")

# random whole nums
print(np.random.randint(
  -10,
  11, 
  size = (3,3)))

[[[0.92044167 0.08761982]
  [0.74210817 0.80984532]]

 [[0.37007556 0.28742253]
  [0.42436365 0.94320149]]] 

[[ 0 -4 -2]
 [-9 -6 10]
 [ 4 10  9]]


In [230]:
colors = np.array([ "bumblebee", "cinnamon", "lava", "mahogany", "moss", "sapphire"])

print(np.random.choice(colors), "\n")
print(np.random.choice(colors, size=(2,2)), "\n")

np.random.shuffle(colors)
print(colors)

sapphire 

[['lava' 'sapphire']
 ['lava' 'sapphire']] 

['mahogany' 'bumblebee' 'moss' 'cinnamon' 'sapphire' 'lava']


In [659]:
squares = np.array([1,4,9,16,25])
degrees = np.arange(-90, 135, 45)
print(degrees)
print(squares-13)
print(squares * degrees)
print(np.cos(degrees))

[-90 -45   0  45  90]
[-12  -9  -4   3  12]
[ -90 -180    0  720 2250]
[-0.44807362  0.52532199  1.          0.52532199 -0.44807362]


In [660]:
stats = [[-2, -3, -7],[10, -8,  1],[ 7,  4, -2]]
print(np.max(stats), "\n")
print(np.max(stats, axis = 0), "\n")
print(np.min(stats, axis = 1), "\n")

10 

[10  4  1] 

[-7 -8 -2] 



In [458]:
stats = [[-2, -3, -7],[10, -8,  1],[ 7,  4, -2]]
stats_b = stats
stats_copy = stats.copy()

# print(stats_b)
# print(stats_copy, "\n")

stats[0]
stats[0] = [99,99,99]

print(stats_b)
print(stats_copy)

[[99, 99, 99], [10, -8, 1], [7, 4, -2]]
[[-2, -3, -7], [10, -8, 1], [7, 4, -2]]
